import random from "lodash.random";

export enum QUESTION_TYPE {
  ENTER_FOREIGN_WORD,
  ENTER_FOREIGN_WORD_BY_AUDIO,
  SELECT_FOREIGN_WORD,
  SELECT_FOREIGN_WORD_BY_AUDIO,
  SELECT_TRANSLATION,
}

export function getRandomQuestionType() {
  return 4;
  return [
    QUESTION_TYPE.ENTER_FOREIGN_WORD,
    QUESTION_TYPE.ENTER_FOREIGN_WORD_BY_AUDIO,
    QUESTION_TYPE.SELECT_FOREIGN_WORD,
    QUESTION_TYPE.SELECT_FOREIGN_WORD_BY_AUDIO,
    QUESTION_TYPE.SELECT_TRANSLATION,
  ][random(0, 4)];
}

export const VARIANT_NUMBER = 4;
